name: Generate Manifest

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.lua'

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate Manifest
      run: bash ./manifest.sh

    - name: Setup Git
      run: |-
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        git add manifest.json
        git commit -m "Generate new manifest"
        git push origin master
