name: Generate Manifest

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.lua'

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate Manifest
      run: bash ./manifest.sh

    - name: commit
      run: |
        git checkout master
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions@github.com"
        git add manifest.json
        git commit -m "Generate new manifest"
        git push
